Bug 1918910: Only log error on nonexistent instance type for scale from zero
openshift/cluster-api-provider-gcp pull request #157
Opened 2021-03-25 11:27 UTC by Danil-Grigorev

Prevent endless reconciles for machineSet due to failed attempt to set scale from zero annotation when the instance type is missing in our static list.

2021-03-25 11:34 UTC, JoelSpeed approved these changes
/approve

Looks great, thanks

2021-03-25 14:36 UTC, elmiko requested changes
looks mostly good, one small nit

2021-03-25 14:36 UTC, elmiko commented on pkg/cloud/gcp/actuators/machineset/cache.go
> +		klog.Error("Autoscaling from zero will not work. To fix this, manually populate machine annotations for you instance type: %v", []string{cpuKey, memoryKey})
```suggestion
		klog.Error("Autoscaling from zero will not work. To fix this, manually populate machine annotations for your instance type: %v", []string{cpuKey, memoryKey})
```

2021-03-25 14:59 UTC, elmiko approved these changes
thanks Danil
/lgtm

2021-03-25 16:34 UTC, Danil-Grigorev commented
/hold 

Needs a fix of error code :D 404 is not it, API returns 400 for unknown zone

2021-03-25 16:48 UTC, Danil-Grigorev commented
NVM, it is the same line of code, just a different domain. Will need a separate PR after that.
/hold cancel

2021-04-08 09:48 UTC, JoelSpeed commented
/override ci/prow/e2e-gcp-operator

This [passed except from the webhook tests](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-gcp/157/pull-ci-openshift-cluster-api-provider-gcp-master-e2e-gcp-operator/1380037542430117888) which are known to be broken, I'm confident this change is ok

2021-04-09 12:11 UTC, JoelSpeed commented
/retest

2021-04-10 10:41 UTC, merged